name: Build Android APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 1. Setup Java 17 (Wajib buat Android 12+)
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # 3. Setup Gradle 8.7 (Biar stabil)
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: '8.7'

      # 4. Install Cordova
      - name: Install Cordova
        run: npm install -g cordova

      # 5. Install Plugin & Dependencies
      - name: Install Dependencies
        run: npm install

      # 6. PASANG PLATFORM ANDROID (Ini yang tadi eror/lupa)
      - name: Add Android Platform
        run: |
            cordova platform remove android || true
            cordova platform add android@13.0.0

      # 7. Build APK
      - name: Build APK
        run: cordova build android --debug

      # 8. Upload Hasil
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: wa-bluetooth-apk
          path: platforms/android/app/build/outputs/apk/debug/app-debug.apk
